(define anthy-use-prediction? #f)
(define anthy-select-prediction-by-numeral-key? #f)
(define anthy-use-implicit-commit-prediction? #t)
(define anthy-use-with-vi? #f)
(define anthy-use-mode-transition-keys-in-off-mode? #f)
