{
    directory => "dotfiles",
    files => [
        'bin',
        '.vim',
        '.vimrc',
        '.gvimrc',
        '.vimperator',
        '.vimperatorrc',
        '.bash_profile',
        '.bashrc',
        '.screenrc',
        '.inputrc',
        '.zshrc',
        '.zshenv',
        '.zsh',
        '.skel',
        '.module-starter',
        '.w3m/keymap',
        '.Xmodmap',
        '.shrc.common',
        '.shrc.cygwin',
        '.shrc.start-screen',
        '.env.common',
        '.tmux.conf',
        '.tmux',
        '.uim',
        '.uim.d/customs',
    ],
    os_files => {map {
        $_ => {
            '.vimperator' => 'vimperator',
            '.vimperatorrc' => '_vimperatorrc',
        }
    } qw(MSWin32 cygwin)},
    ignore_files => [
        '.vim/backup',
        '.vim/.netrwhist',
        '.vim/.VimballRecord',
        '.vim/info',
        '.vim/record',
        '.vim/sessions',
        '.vim/swap',
        '.vimperator/info',
    ],
}
