#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

# gnu_compat: --opt="..." is allowed.
# no_bundling: single character option is not bundled.
# no_ignore_case: no ignore case on long option.
use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);
use FindBin qw($Bin);
use Pod::Usage;
use File::Spec::Functions qw(catfile);
use File::Path qw(rmtree);
use File::Basename qw(dirname);

use lib "$Bin/lib";
use Dotfiles::Util;


### sub ###
sub usage () {
    pod2usage(-verbose => 2);
}


### main ###
chdir $Bin or die "$Bin:$!";

my $home;
my $username;
my $config_file = 'files.yaml';

my ($needhelp);
GetOptions(
    'h|help'
        => \$needhelp,
    'u|username=s'
        => \$username,
    'c|config-file=s'
        => \$config_file,
) or usage;
usage if $needhelp;


if (defined $username) {
    $home = get_home_from_user $username;
}
else {
    ($username, $home) = determine_user_and_home;
}

my $c = load_config($config_file);

for my $file (@{$c->{files}}) {
    my ($src, $dest);

    if (is_mswin() && exists $c->{mswin_files}{$file}) {
        $src  = $file;
        $dest = catfile($home, $c->{mswin_files}{$file});
    }
    else {
        $src  = $file;
        $dest = catfile($home, $file);
    }

    install($src, $dest, $username);
}




__END__

=head1 NAME

    extract-dotfiles - NO DESCRIPTION YET.


=head1 SYNOPSIS


=head1 OPTIONS


=head1 AUTHOR

tyru <tyru.exe@gmail.com>
