#!/bin/sh

file=`tempfile`
vim -S write-runtimepath.vim "$file"

cat "$file" | while read rtp_path; do
    # git rev-parse --git-dir:
    #   Check if $rtp_path is git repository.
    ( \
        cd "$rtp_path" >/dev/null 2>&1 && \
        git rev-parse --git-dir >/dev/null 2>&1 && \
        git ls-files \
    ) | while read rtp_file; do
        cp $rtp_path/$rtp_file $rtp_file
    done
done
