#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

use FindBin ();
use File::Path qw(rmtree);
use IO::Handle;
use File::Spec::Functions qw(catfile);
use File::Temp ();

use lib "$FindBin::Bin/lib";
use Dotfiles::Util;

# gnu_compat: --opt="..." is allowed.
# no_bundling: single character option is not bundled.
# no_ignore_case: no ignore case on long option.
use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);



### sub ###

sub usage () {
    die <<EOF;
    Usage: $0 [OPTIONS]

OPTIONS:
    -h, --help                  show this help.
    -u, --username <user>       specify username.
EOF
}



### main ###

# chdir parent directory of this script
chdir $FindBin::Bin or die "$FindBin::Bin:$!";

my $home;
my $username;
my $config_file = 'files.yaml';

my $needhelp;
GetOptions(
    'h|help'
        => \$needhelp,
    'u|username=s'
        => \$username,
    'c|config-file=s'
        => \$config_file,
) or usage;
usage if $needhelp;


if (defined $username) {
    $home = get_home_from_user $username;
}
else {
    ($username, $home) = determine_user_and_home;
}

my $c = load_config($config_file);

for my $file (map { convert_filename $c, $_ } @{$c->{files}}) {
    my ($src, $dest);

    $src  = catfile($home, $file);
    $dest = $file;

    say("$src -> $dest");
    install($src, $dest, $username);
}

for my $f (@{$c->{removed_files}}) {
    if (-e $f) {
        rmtree($f) or warn "cannot remove $_: $!";
    }
}
